version: 2

sphinx:
  configuration: _doc/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

python:
  install:
    - requirements: requirements.txt
    - method: setuptools
      path: .
