name: saul
channels:
  - conda-forge
dependencies:
  - matplotlib<3.10  # Fixes: AttributeError: 'NoneType' object has no attribute 'axis'
  - multitaper
  - obspy
  - pandas
  - pip
  - pip:
      - git+https://github.com/uafgeotools/waveform_collection.git
      - git+https://code.usgs.gov/ghsc/esi/esi-core.git
      - --editable .
