name: saul
channels:
  - conda-forge
dependencies:
  - multitaper
  - obspy
  - pandas
  - pip
  - python<3.13  # https://code.usgs.gov/ghsc/esi/esi-core/-/blob/02bf020880a916b1538adf404da112a64b7b9b89/pyproject.toml#L31
  - stockwell
  - pip:
      - git+https://github.com/uafgeotools/waveform_collection.git
      - git+https://code.usgs.gov/ghsc/esi/esi-core.git
      - --editable .
