[project]
name = "SAUL"
version = "2026.9"
requires-python = ">=3.11,<3.14"
dependencies = [
    "esi-core",  # https://code.usgs.gov/ghsc/esi/esi-core
    "multitaper",  # https://github.com/gaprieto/multitaper
    "obspy",
    "pandas",
    "stockwell",  # https://github.com/claudiodsf/stockwell
    "waveform_collection @ git+https://github.com/uafgeotools/waveform_collection.git",
]

[project.optional-dependencies]
dev = [
    "black",
    "ipython",
    "isort",
]

[dependency-groups]
docs = [
    "sphinx",
    "sphinx-autobuild",
    "sphinx-rtd-theme",
]

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-root = ""

[tool.black]
skip-string-normalization = true

[tool.isort]
profile = "black"
