[build-system]
requires = ["hatchling", "uv-dynamic-versioning"]
build-backend = "hatchling.build"

[project]
name = "saul"
dynamic = ["version"]
requires-python = ">=3.11,<3.14"
dependencies = [
    "esi-core",  # https://code.usgs.gov/ghsc/esi/esi-core
    "ipython",
    "lxml",
    "matplotlib",
    "multitaper",  # https://github.com/gaprieto/multitaper
    "numpy",
    "obspy",
    "pandas",
    "requests",
    "scipy",
    "stockwell",  # https://github.com/claudiodsf/stockwell
]

[dependency-groups]
tooling = ["poethepoet"]
lint = ["ruff"]
docs = [
    "sphinx",
    "sphinx-autobuild",
    "sphinx-rtd-theme",
]

[tool.hatch.version]
source = "uv-dynamic-versioning"

[tool.hatch.build.targets.wheel]
packages = ["src/saul"]

[tool.poe.env]
TARGET_FILES = "src/ examples/ docs/"

[tool.poe.tasks]
docs = "sphinx-build docs/ docs/_build/ --fail-on-warning"
_lint = "ruff check ${TARGET_FILES}"
_format = "ruff format ${TARGET_FILES}"
format = ["_lint --select I --fix", "_format"]
check = ["_lint", "_format --check"]

[tool.ruff.format]
quote-style = "single"
