[project]
name = "SAUL"
dynamic = ["version"]
requires-python = ">=3.11,<3.14"
dependencies = [
    "esi-core",  # https://code.usgs.gov/ghsc/esi/esi-core
    "ipython",
    "multitaper",  # https://github.com/gaprieto/multitaper
    "obspy",
    "pandas",
    "stockwell",  # https://github.com/claudiodsf/stockwell
    "waveform_collection @ git+https://github.com/uafgeotools/waveform_collection.git",
]

[dependency-groups]
dev = [
    "black",
    "isort",
]
docs = [
    "sphinx",
    "sphinx-autobuild",
    "sphinx-rtd-theme",
]

[build-system]
requires = ["hatchling", "uv-dynamic-versioning"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "uv-dynamic-versioning"

[tool.hatch.metadata]
allow-direct-references = true

[tool.black]
skip-string-normalization = true

[tool.isort]
profile = "black"
